/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_peter_easytouchdemo_MainService */

#ifndef _Included_com_example_peter_easytouchdemo_MainService
#define _Included_com_example_peter_easytouchdemo_MainService
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
